site_name: UAVSim APP  

theme:
  name: material        # 用 material 主题
  palette:
    primary: blue
  language: zh

plugins:                # 搜索插件
  - search

markdown_extensions:    # 代码高亮插件
  - pymdownx.highlight
  - pymdownx.superfences

nav:                    # 左侧导航栏
#  - 首页: index.md
  - UAVSim: UAVSim.md